Organization:
- Work
  - 1 test: defining functions for part 1, testing on test input
  - 1 run: getting answer for part 1
  - 2 test: ...
  - 2 run: ...
- Utilities: functions I think might help parse general inputs
- Inputs: where I define the test (_t_) and problem (_s_) inputs

# Work

## 1 test

In [88]:
import numpy as np

In [89]:
# Basic input parsing
locations = np.array([list(block) for block in split(t)])
n, m = locations.shape
locations

array([['S', 'a', 'b', 'q', 'p', 'o', 'n', 'm'],
       ['a', 'b', 'c', 'r', 'y', 'x', 'x', 'l'],
       ['a', 'c', 'c', 's', 'z', 'E', 'x', 'k'],
       ['a', 'c', 'c', 't', 'u', 'v', 'w', 'j'],
       ['a', 'b', 'd', 'e', 'f', 'g', 'h', 'i']], dtype='<U1')

In [90]:
# Start/end locations
for i in range(n):
    for j in range(m):
        if locations[i,j] == 'S':
            loc_start = (i,j)
        if locations[i,j] == 'E':
            loc_end = (i,j)
print(loc_start, loc_end)

(0, 0) (2, 5)


In [91]:
ord('a') - 96

1

In [92]:
def get_height(x):
    if x == 'S':
        return 1
    if x == 'E':
        return 26
    return ord(x) - 96

In [93]:
# Convert to heights
heights = np.array([[get_height(x) for x in row] for row in locations])
heights

array([[ 1,  1,  2, 17, 16, 15, 14, 13],
       [ 1,  2,  3, 18, 25, 24, 24, 12],
       [ 1,  3,  3, 19, 26, 26, 24, 11],
       [ 1,  3,  3, 20, 21, 22, 23, 10],
       [ 1,  2,  4,  5,  6,  7,  8,  9]])

In [94]:
# Convert array indices to a linear index
def ij_to_k(i,j,n,m):
    return i*m + j

# Get the neighbors of an ij
def neighbors(i,j,n,m):
    neighbors = []
    if i > 0:
        neighbors += [(i-1,j)]
    if i < n-1:
        neighbors += [(i+1,j)]
    if j > 0:
        neighbors += [(i,j-1)]
    if j < m-1:
        neighbors += [(i,j+1)]
    return neighbors

In [95]:
ij_to_k(1,0,n,m)

8

In [96]:
# Form the adjacency matrix
A = np.zeros((n*m,n*m))

for i in range(n):
    for j in range(m):
        k = ij_to_k(i,j,n,m)
        
        for ip, jp in neighbors(i,j,n,m):
            if heights[ip,jp] <= heights[i,j] + 1:
                kp = ij_to_k(ip,jp,n,m)
                A[k,kp] = 1

In [97]:
A

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 1., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [98]:
heights

array([[ 1,  1,  2, 17, 16, 15, 14, 13],
       [ 1,  2,  3, 18, 25, 24, 24, 12],
       [ 1,  3,  3, 19, 26, 26, 24, 11],
       [ 1,  3,  3, 20, 21, 22, 23, 10],
       [ 1,  2,  4,  5,  6,  7,  8,  9]])

In [99]:
from scipy.sparse.csgraph import dijkstra

In [100]:
ks = ij_to_k(*loc_start, n, m)
ke = ij_to_k(*loc_end, n, m)
print(ks, ke)

0 21


In [83]:
int(dijkstra(A, indices=[ks])[0,ke])

31

## 1 run

In [109]:
# Basic parsing
locations = np.array([list(block) for block in split(s)])
n, m = locations.shape
print(n, m)

# Start/end locations
for i in range(n):
    for j in range(m):
        if locations[i,j] == 'S':
            loc_start = (i,j)
        if locations[i,j] == 'E':
            loc_end = (i,j)
print(loc_start, loc_end)

# Heights
heights = np.array([[get_height(x) for x in row] for row in locations])

# Form the adjacency matrix
A = np.zeros((n*m,n*m))
for i in range(n):
    for j in range(m):
        k = ij_to_k(i,j,n,m)
        
        for ip, jp in neighbors(i,j,n,m):
            if heights[ip,jp] <= heights[i,j] + 1:
                kp = ij_to_k(ip,jp,n,m)
                A[k,kp] = 1

41 161
(20, 0) (20, 139)


In [110]:
ks = ij_to_k(*loc_start, n, m)
ke = ij_to_k(*loc_end, n, m)
print(ks, ke)

3220 3359


In [87]:
int(dijkstra(A, indices=[ks])[0,ke])

481

## 2 test

Run the above to set the adjacency matrix and ks, ke

In [102]:
# Get indices of locations with height 1
Ka = []
for i in range(n):
    for j in range(m):
        if heights[i,j] == 1:
            Ka += [ij_to_k(i,j,n,m)]
Ka

[0, 1, 8, 16, 24, 32]

In [108]:
# Get the distance from the Ka to ke
D = dijkstra(A, indices=Ka)[:,ke]

# Get the shortest distance
int(D.min())

29

## 2 run

In [111]:
# Get indices of locations with height 1
Ka = []
for i in range(n):
    for j in range(m):
        if heights[i,j] == 1:
            Ka += [ij_to_k(i,j,n,m)]
Ka

[0,
 13,
 14,
 15,
 16,
 17,
 25,
 26,
 27,
 28,
 29,
 30,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 96,
 97,
 98,
 99,
 100,
 101,
 109,
 119,
 120,
 123,
 124,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 186,
 187,
 188,
 189,
 190,
 191,
 200,
 201,
 212,
 213,
 214,
 215,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 257,
 258,
 259,
 260,
 261,
 262,
 267,
 268,
 269,
 270,
 280,
 281,
 282,
 283,
 284,
 285,
 318,
 319,
 320,
 321,
 322,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 347,
 348,
 349,
 350,
 351,
 360,
 361,
 362,
 363,
 373,
 374,
 375,
 376,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 418,
 419,
 420,
 421,
 422,
 428,
 429,
 430,
 431,
 432,
 433,
 442,
 443,
 444,
 445,
 446,
 458,
 459,
 460,
 479,
 480,
 481,
 482,
 483,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 509,
 510,
 511,
 512,
 513,
 521,
 522,
 523,
 524,
 534,
 535,
 536,
 537,
 543,
 544,

In [112]:
# Get the distance from the Ka to ke
D = dijkstra(A, indices=Ka)[:,ke]

# Get the shortest distance
int(D.min())

480

# Utilities

In [54]:
# Remove initial/final \n characters
def clean(s):
    return s[1:-1]

# Split at \n characters
# If there are \n\n characters, split into blocks too
def split(s, block_char = '\n\n', line_char = '\n'):
    out = [block.split(line_char) for block in clean(s).split(block_char)]
    if len(out) == 1:
        return out[0]
    else:
        return out

# Apply a function(s) to a list or "block" data (2-level list)
def apply_func(data, func, nested=False):
    if not isinstance(func, list):
        func = [func]
        
    def _func(x):
        for f in func:
            x = f(x)
        return x
        
    if nested:
        return [[_func(x) for x in block] for block in data]
    else:
        return [_func(x) for x in data]

# Split, parsing everything as ints
def split_int(s):
    return apply_func(split(s), int)

# Split, parsing everything as float
def split_float(s):
    return apply_func(split(s), float)

# Inputs

In [55]:
t = """
Sab...
...
abd...
"""

In [56]:
s = """
abc...
...
abc...
"""