In [1]:
import numpy as np
import pandas as pd
import math
import scipy
import sys

In [51]:
def visit_side_positions(array_visit, array_in, x, y):
    ret = []
    for i in range(-1,2):
        for j in range(-1,2):
            if i != 0 and j != 0:
                continue
            ii = x+i
            jj = y+j
            if (ii >= 0) and (ii < array_in.shape[0]) and (jj >= 0) and (jj < array_in.shape[1]):
                ## within shape
                if ((array_in[ii,jj] - array_in[x,y]) <= 1) and (array_visit[ii,jj] == -1 or array_visit[ii,jj] > array_visit[x,y]+1):
                    ret.append((ii,jj))
    return ret

In [86]:
file1 = open('12.txt', 'r')
lines = file1.readlines()
start_pt = ()
end_pt = ()


array_in = np.array([[ord(c)-97 for c in l.replace('\n','').replace('S','`').replace('E','{')] for l in lines])
array_in

array_visit = np.zeros(array_in.shape) - 1
array_visit

for i in range(array_in.shape[0]):
    for j in range(array_in.shape[1]):
        if array_in[i,j] == -1:
            start_pt = (i,j)
            array_visit[i,j] = 0
        elif array_in[i,j] == 26:
            end_pt = (i,j)

# for l in lines:
#     l_split = l.replace('\n','')


In [87]:
# array_visit = np.zeros(array_in.shape)
array_visit

expanded = True
while expanded:
    array_visit_new = array_visit.copy()
    expanded = False
    for i in range(array_in.shape[0]):
        for j in range(array_in.shape[1]):
            if array_visit[i,j] != -1:
                # print(f'({i},{j}) should visit: {visit_side_positions(array_visit,array_in,i,j)}')
                for x,y in visit_side_positions(array_visit,array_in,i,j):
                    array_visit_new[x,y] = array_visit[i,j] + 1
                    expanded = True
    # print(array_visit)
    array_visit = array_visit_new

In [88]:
array_visit

array([[ 0.,  1.,  2., 19., 18., 17., 16., 15.],
       [ 1.,  2.,  3., 20., 29., 28., 27., 14.],
       [ 2.,  3.,  4., 21., 30., 31., 26., 13.],
       [ 3.,  4.,  5., 22., 23., 24., 25., 12.],
       [ 4.,  5.,  6.,  7.,  8.,  9., 10., 11.]])

In [89]:
array_in

array([[-1,  0,  1, 16, 15, 14, 13, 12],
       [ 0,  1,  2, 17, 24, 23, 23, 11],
       [ 0,  2,  2, 18, 25, 26, 23, 10],
       [ 0,  2,  2, 19, 20, 21, 22,  9],
       [ 0,  1,  3,  4,  5,  6,  7,  8]])

In [90]:
array_visit[end_pt]

31.0

# Second part

we need to switch heights and find the minimum from the start pt (old end pt) to any pt with height 25

In [106]:
start_pt = ()

array_in = np.array([[25 - (ord(c)-97) for c in l.replace('\n','').replace('S','`').replace('E','{')] for l in lines])
array_in

array_visit = np.zeros(array_in.shape) - 1
array_in

for i in range(array_in.shape[0]):
    for j in range(array_in.shape[1]):
        if array_in[i,j] == -1:
            start_pt = (i,j)
            array_visit[i,j] = 0

# array_in


In [107]:
# array_visit = np.zeros(array_in.shape)
array_visit

expanded = True
while expanded:
    array_visit_new = array_visit.copy()
    expanded = False
    for i in range(array_in.shape[0]):
        for j in range(array_in.shape[1]):
            if array_visit[i,j] != -1:
                # print(f'({i},{j}) should visit: {visit_side_positions(array_visit,array_in,i,j)}')
                for x,y in visit_side_positions(array_visit,array_in,i,j):
                    array_visit_new[x,y] = array_visit[i,j] + 1
                    expanded = True
    # print(array_visit)
    array_visit = array_visit_new

In [108]:
array_visit

array([[403., 402., 403., ...,  -1.,  -1.,  -1.],
       [402., 401., 402., ...,  -1.,  -1.,  -1.],
       [401., 400., 401., ...,  -1.,  -1.,  -1.],
       ...,
       [389., 388., 389., ...,  -1.,  -1.,  -1.],
       [390., 389., 390., ...,  -1.,  -1.,  -1.],
       [391., 390., 391., ...,  -1.,  -1.,  -1.]])

In [109]:
array_in

array([[25, 24, 25, ..., 25, 25, 25],
       [25, 24, 25, ..., 25, 25, 25],
       [25, 24, 25, ..., 25, 25, 25],
       ...,
       [25, 24, 25, ..., 25, 25, 25],
       [25, 24, 23, ..., 25, 25, 25],
       [25, 24, 23, ..., 25, 25, 25]])

In [111]:
best = 9999

for i in range(array_in.shape[0]):
    for j in range(array_in.shape[1]):
        if array_in[i,j] == 25 and best > array_visit[i,j] and array_visit[i,j] > 0:
            print(f'old best: {best}, new best: {array_visit[i,j]}, start_pt: {start_pt}')
            best = array_visit[i,j]

old best: 9999, new best: 403.0, start_pt: (20, 43)
old best: 403.0, new best: 402.0, start_pt: (20, 43)
old best: 402.0, new best: 401.0, start_pt: (20, 43)
old best: 401.0, new best: 400.0, start_pt: (20, 43)
old best: 400.0, new best: 399.0, start_pt: (20, 43)
old best: 399.0, new best: 398.0, start_pt: (20, 43)
old best: 398.0, new best: 397.0, start_pt: (20, 43)
old best: 397.0, new best: 396.0, start_pt: (20, 43)
old best: 396.0, new best: 395.0, start_pt: (20, 43)
old best: 395.0, new best: 394.0, start_pt: (20, 43)
old best: 394.0, new best: 393.0, start_pt: (20, 43)
old best: 393.0, new best: 392.0, start_pt: (20, 43)
old best: 392.0, new best: 391.0, start_pt: (20, 43)
old best: 391.0, new best: 390.0, start_pt: (20, 43)
old best: 390.0, new best: 389.0, start_pt: (20, 43)
old best: 389.0, new best: 388.0, start_pt: (20, 43)
old best: 388.0, new best: 387.0, start_pt: (20, 43)
old best: 387.0, new best: 386.0, start_pt: (20, 43)
old best: 386.0, new best: 385.0, start_pt: (20